apiVersion: apps/v1
kind: Deployment
metadata:
 name: orderitem-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: custms
 template:
  metadata:
   labels:
    app: custms
  spec:
   imagePullSecrets:
   - name: vinodh
   containers:  
   - name: azureict
     image: azureict.azurecr.io/orderwebapi:latest
     imagePullPolicy: Always
     env:
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: customerms-service
spec:
 type: LoadBalancer
 ports:
   - port: 80
 selector:
   app: custms